Styl/home
Pluteers/petmily-flutter-app pull request #14
Opened 2023-04-27 03:27 UTC by devpark435

- Home, Channel 2가지 스크린 UI 작업했습니다.
- Data는 임시로 Class 배열 생성해서 작업했습니다.
<hr>
<div align="center">
 <p align="center"> Snapshot </p>
 <img width="300" alt="HomeScreen Styling ScreenShot" src="https://user-images.githubusercontent.com/112539563/234751798-1c84f444-a2ec-4256-bc4f-a34083fee87c.png">
 <img width="300" alt="ChannelScreen Styling ScreenShot" src="https://user-images.githubusercontent.com/112539563/234751835-e8a7cb90-8fc5-4d1c-bc71-4f4933a34782.png">
</div>

2023-04-27 04:13 UTC, yujinkim1 reviewed
리뷰 작성했어요~ 답변 부탁해요 @devpark435

2023-04-27 04:13 UTC, yujinkim1 commented on .vscode/launch.json
> +        },
@devpark435 
기존 `launch.json` configure 리스트에서 퀵 디버그를 사용하기 위해서 추가 했던 구문은 삭제할게요!

2023-04-27 04:13 UTC, yujinkim1 commented on lib/screens/channel.dart
> +        ]),
@devpark435 
다음 작업 진행 할때 close lint 정렬하면 더 예쁠 것 같아요!

2023-04-27 04:13 UTC, yujinkim1 commented on lib/screens/home.dart
> +        }),
@devpark435 
이 부분도 close lint 정렬하면 예쁠 것 같네요!

2023-05-01 03:02 UTC, devpark435 commented on lib/screens/channel.dart
> +        ]),
참고하도록 하겠습니다~

2023-05-01 03:03 UTC, devpark435 commented on lib/screens/home.dart
> +        }),
참고하도록 하겠습니다~2

2023-05-01 03:03 UTC, devpark435 commented on .vscode/launch.json
> +        },
헉 깜빡했네요 삭제확인했습니다

2023-05-01 03:17 UTC, yujinkim1 commented on lib/screens/channel.dart
> +        ]),
확인했어요!

2023-05-01 03:19 UTC, yujinkim1 requested changes
확인했어요

2023-05-01 03:19 UTC, yujinkim1 approved these changes

2023-05-01 03:19 UTC, merged